
import { Chef, CultureStory } from './types';

export const MOCK_CULTURE_STORIES: CultureStory[] = [
  {
    id: 's1',
    title: 'La Vera Storia della Carbonara',
    country: 'Italia',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=1200&q=80',
    content: 'Molti storici tracciano le sue origini al 1944 a Roma, dall\'incontro tra la pasta italiana e le razioni dei soldati americani (bacon e uova). La MESA protegge la ricetta purista: solo guanciale, pecorino romano, tuorlo e pepe nero.',
    funFact: 'In origine non esisteva una ricetta fissa: la panna era usata comunemente fino agli anni \'80!'
  },
  {
    id: 's2',
    title: 'Jollof Rice: La Sfida dell\'Africa Occidentale',
    country: 'Nigeria',
    flag: '🇳🇬',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1200&q=80',
    content: 'Nessun piatto accende gli animi come il Jollof. Una base di riso, pomodoro e spezie che crea una competizione amichevole tra Nigeria e Ghana su chi detenga la ricetta migliore.',
    funFact: 'Il segreto di un buon Jollof è l\'aroma affumicato che si ottiene cuocendolo sul fuoco di legna.'
  },
  {
    id: 's3',
    title: 'Sushi: Oltre il Pesce Crudo',
    country: 'Giappone',
    flag: '🇯🇵',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80',
    content: 'Nato come metodo di conservazione del pesce nel riso fermentato, il sushi si è evoluto nell\'Edo-mae stile nel 1800, diventando il fast food d\'eccellenza dei mercati di Tokyo.',
    funFact: 'Originariamente, il riso veniva scartato e si mangiava solo il pesce!'
  },
  {
    id: 's4',
    title: 'Thieboudienne: L\'Oro del Senegal',
    country: 'Senegal',
    flag: '🇸🇳',
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=1200&q=80',
    content: 'Dichiarato patrimonio UNESCO, è il piatto nazionale del Senegal. Riso, pesce fresco e verdure cotte in un brodo di pomodoro speziato che rappresenta l\'essenza della Teranga (ospitalità).',
    funFact: 'La parola deriva dal Wolof "Ceebu Jën", che significa letteralmente "riso con pesce".'
  },
  {
    id: 's5',
    title: 'Ceviche: L\'Anima del Perù',
    country: 'Perù',
    flag: '🇵🇪',
    image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=1200&q=80',
    content: 'Pesce crudo marinato nel succo di lime, peperoncino e cipolla. Un piatto che combina freschezza oceanica e tradizioni pre-colombiane dei popoli Moche.',
    funFact: 'Il "Leche de Tigre" è il succo della marinatura, considerato un potente ricostituente.'
  },
  {
    id: 's6',
    title: 'Tagine: La Magia della Terracotta',
    country: 'Marocco',
    flag: '🇲🇦',
    image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2895?auto=format&fit=crop&w=1200&q=80',
    content: 'Prende il nome dal piatto di terracotta con coperchio conico in cui viene cucinato. Il vapore ricircola mantenendo la carne tenerissima con l\'uso di spezie, prugne e mandorle.',
    funFact: 'Il coperchio conico serve a condensare il vapore e farlo ricadere sul cibo, ideale per climi con poca acqua.'
  },
  {
    id: 's7',
    title: 'Attiéké: Il Couscous di Manioca',
    country: 'Costa d\'Avorio',
    flag: '🇨🇮',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80',
    content: 'Leggero e granuloso, l\'Attiéké è fatto di manioca fermentata e grattugiata. È l\'accompagnamento perfetto per il pesce grigliato e l\'alloco (platano fritto).',
    funFact: 'È diventato così popolare che ora viene esportato in tutto il mondo in versioni disidratate.'
  },
  {
    id: 's8',
    title: 'Pho: Il Mattino di Hanoi',
    country: 'Vietnam',
    flag: '🇻🇳',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80',
    content: 'Una zuppa di noodles di riso profumata con cannella, anice stellato e zenzero. Un piatto che racconta l\'influenza coloniale francese unita alle tradizioni asiatiche.',
    funFact: 'In Vietnam, il Pho è principalmente un piatto da colazione consumato per strada.'
  },
  {
    id: 's9',
    title: 'Mole Poblano: Il Sincretismo in Salsa',
    country: 'Messico',
    flag: '🇲🇽',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=80',
    content: 'Una salsa complessa che include cioccolato fondente, peperoncini, spezie e semi. Rappresenta l\'unione perfetta tra il mondo azteco e quello spagnolo.',
    funFact: 'Esistono oltre 50 varianti diverse di mole, ognuna con un segreto familiare tramandato.'
  },
  {
    id: 's10',
    title: 'Pizza Margherita: Un Omaggio Reale',
    country: 'Italia',
    flag: '🇮🇹',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad50?auto=format&fit=crop&w=1200&q=80',
    content: 'Creata nel 1889 da Raffaele Esposito in onore della Regina Margherita di Savoia, con i colori della bandiera italiana: pomodoro, mozzarella e basilico.',
    funFact: 'La pizza era originariamente un cibo povero venduto nelle strade di Napoli già dal 1700.'
  },
  {
    id: 's11',
    title: 'Zighinì: Il Piatto della Condivisione',
    country: 'Etiopia',
    flag: '🇪🇹',
    image: 'https://images.unsplash.com/photo-1542354256-4b68e7d7f26c?auto=format&fit=crop&w=1200&q=80',
    content: 'Uno stufato di carne piccante servito sull\'Injera, un pane spugnoso e acido che funge da piatto e posata. Si mangia rigorosamente con le mani in segno di amicizia.',
    funFact: 'L\'Injera è fatta di Teff, un cereale antichissimo privo di glutine.'
  },
  {
    id: 's12',
    title: 'Ratatouille: La Semplicità Provenzale',
    country: 'Francia',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1572453860999-1ad12413b538?auto=format&fit=crop&w=1200&q=80',
    content: 'Nata a Nizza come stufato povero dei contadini provenzali, che usavano tutte le verdure estive dell\'orto. Oggi è simbolo della cucina francese raffinata.',
    funFact: 'La parola "touille" significa "rimestare", l\'azione principale per prepararla.'
  },
  {
    id: 's13',
    title: 'Pad Thai: Orgoglio Nazionale',
    country: 'Thailandia',
    flag: '🇹🇭',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
    content: 'Nato negli anni \'30 per promuovere l\'identità thailandese, è l\'equilibrio perfetto tra dolce, salato, acido e piccante. Noodles di riso saltati con tamarindo e arachidi.',
    funFact: 'Fu il governo thailandese a lanciarlo come "piatto nazionale" per ridurre il consumo di riso durante la guerra.'
  },
  {
    id: 's14',
    title: 'Koshary: Il Mix Egiziano',
    country: 'Egitto',
    flag: '🇪🇬',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=1200&q=80',
    content: 'Pasta, riso e lenticchie con una salsa di pomodoro speziata e cipolle fritte. È il comfort food per eccellenza delle strade del Cairo.',
    funFact: 'Nonostante sia il piatto nazionale egiziano, ha origini indiane (dal Khichdi).'
  },
  {
    id: 's15',
    title: 'Feijoada: Il Ritmo del Brasile',
    country: 'Brasile',
    flag: '🇧🇷',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
    content: 'Uno stufato denso di fagioli neri e diversi tagli di carne di maiale. È il piatto delle celebrazioni, solitamente servito il sabato con riso, cavolo e farofa.',
    funFact: 'È nata dall\'ingegno degli schiavi che utilizzavano i tagli di carne meno pregiati scartati dai proprietari.'
  }
];

export const MOCK_CHEFS: Chef[] = [
  // --- EUROPA (9) ---
  {
    id: 'c1',
    name: 'Nonna Maria',
    nationality: '🇮🇹',
    continent: 'Europa',
    bio: 'Cucina romana autentica e pasta fatta a mano.',
    fullBio: 'Maria cucina da quando aveva 6 anni, imparando dalla nonna tra i vicoli di Trastevere. La sua cucina non accetta compromessi: solo ingredienti del mercato locale e una pazienza infinita per il ragù.',
    avatar: '/images/nonna_maria.png',
    rating: 4.9,
    location: 'Roma, Trastevere',
    distance: 1.2,
    specialties: ['Lasagna', 'Carbonara'],
    availability: ['19:00 - 22:00'],
    availableDays: [1, 2, 3, 4, 5, 6],
    reviews: [{ id: 'r1', author: 'Marco', rating: 5, comment: 'Insuperabile.', date: '2023-10-15' }],
    dishes: [
      { id: 'd1_1', name: 'Lasagna alla Bolognese', description: '5 strati di sfoglia fresca, besciamella vellutata e un ragù cotto 6 ore come vuole la tradizione.', price: 12.50, image: 'https://images.unsplash.com/photo-1574868294417-75902041265e?auto=format&fit=crop&w=800&q=80', chefId: 'c1', tags: ['Carne', 'Pasta'], ingredients: ['Sfoglia all\'uovo', 'Ragù di manzo e maiale', 'Besciamella', 'Parmigiano Reggiano', 'Noce moscata'], preparation: 'Il ragù viene cotto lentamente per 6 ore seguendo la ricetta di famiglia. Gli strati vengono composti a mano e infornati fino a doratura perfetta della superficie.' },
      { id: 'd1_2', name: 'Carbonara di Trastevere', description: 'Rigatoni veraci con guanciale croccante, pecorino romano DOP e crema d\'uova freschissime.', price: 11.00, image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80', chefId: 'c1', tags: ['Carne', 'Pasta'], ingredients: ['Rigatoni', 'Guanciale di Amatrice', 'Pecorino Romano DOP', 'Tuorlo biologico', 'Pepe nero macinato fresco'], preparation: 'Il guanciale viene sudato a fuoco dolce finché non è croccante. La crema si fa rigirando il tuorlo con il pecorino e un cucchiaio di grasso del guanciale. La pasta viene saltata a fuoco spento.' }
    ]
  },
  {
    id: 'c9',
    name: 'Jean-Luc Petit',
    nationality: '🇫🇷',
    continent: 'Europa',
    bio: 'Alta cucina casalinga parigina.',
    fullBio: 'Jean-Luc ha lavorato per anni in piccoli bistrot parigini prima di trasferirsi in Italia. Oggi porta l\'eleganza della cucina francese tra le mura domestiche.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Roma, Parioli',
    distance: 4.2,
    specialties: ['Coq au Vin', 'Ratatouille'],
    availability: ['20:00 - 22:30'],
    availableDays: [2, 3, 4, 5],
    reviews: [],
    dishes: [{ id: 'd9_1', name: 'Coq au Vin', description: 'Pollo ruspante marinato nel vino rosso corposo con funghi, pancetta e cipolline borettane.', price: 19.50, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', chefId: 'c9', tags: ['Carne'] }]
  },
  {
    id: 'c11',
    name: 'Nikos Papadopoulos',
    nationality: '🇬🇷',
    continent: 'Europa',
    bio: 'Mezedes e Moussaka cretesi.',
    fullBio: 'Originario di Creta, Nikos cucina i segreti delle isole greche con olio d\'oliva spremuto a freddo di sua produzione familiare.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Bari, Vecchia',
    distance: 0.5,
    specialties: ['Moussaka', 'Souvlaki'],
    availability: ['12:00 - 22:00'],
    availableDays: [1, 2, 4, 6],
    reviews: [],
    dishes: [{ id: 'd11_1', name: 'Moussaka Tradizionale', description: 'Sformato di melanzane fritte, patate, carne trita speziata e uno strato generoso di besciamella gratinata.', price: 13.00, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80', chefId: 'c11', tags: ['Carne'] }]
  },
  {
    id: 'c27',
    name: 'Hans Mueller',
    nationality: '🇩🇪',
    continent: 'Europa',
    bio: 'Salsicce artigianali e crauti fermentati.',
    fullBio: 'Hans è un maestro della fermentazione. Ogni crauto servito nel suo menu è fermentato naturalmente per almeno 4 settimane secondo ricette bavaresi.',
    avatar: 'https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=400&q=80',
    rating: 4.5,
    location: 'Bolzano, Gries',
    distance: 1.0,
    specialties: ['Wurst', 'Schnitzel'],
    availability: ['18:00 - 22:00'],
    availableDays: [1, 2, 3, 4, 5],
    reviews: [],
    dishes: [{ id: 'd27_1', name: 'Bratwurst & Sauerkraut', description: 'Coppia di salsicce bianche alla griglia servite con crauti artigianali e senape dolce.', price: 13.00, image: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80', chefId: 'c27', tags: ['Carne'] }]
  },
  {
    id: 'c28',
    name: 'Maria Silva',
    nationality: '🇵🇹',
    continent: 'Europa',
    bio: 'Baccalà in 100 modi diversi.',
    fullBio: 'Si dice che in Portogallo ci sia una ricetta di baccalà per ogni giorno dell\'anno. Maria ne conosce almeno 50 e le prepara con amore a Genova.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Genova, Albaro',
    distance: 2.9,
    specialties: ['Bacalhau', 'Pastéis de Nata'],
    availability: ['12:00 - 20:00'],
    availableDays: [2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd28_1', name: 'Bacalhau à Brás', description: 'Baccalà sminuzzato con patatine sottili fritte, cipolla, uova, olive nere e prezzemolo fresco.', price: 16.00, image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80', chefId: 'c28', tags: ['Pesce'] }]
  },
  {
    id: 'c31',
    name: 'Sven Larsson',
    nationality: '🇸🇪',
    continent: 'Europa',
    bio: 'Köttbullar e sapori scandinavi.',
    fullBio: 'Sven porta i sapori del Nord a Milano. Le sue polpette non sono quelle del supermercato: usano carne di alta qualità e una salsa segreta.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
    location: 'Milano, Porta Romana',
    distance: 2.2,
    specialties: ['Meatballs', 'Gravlax'],
    availability: ['19:00 - 21:30'],
    availableDays: [1, 3, 5],
    reviews: [],
    dishes: [{ id: 'd31_1', name: 'Swedish Meatballs', description: 'Polpettine saporite servite con purè di patate cremoso, salsa gravy e marmellata di mirtilli rossi.', price: 14.00, image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9583b5?auto=format&fit=crop&w=800&q=80', chefId: 'c31', tags: ['Carne'] }]
  },
  {
    id: 'c32',
    name: 'Don Calogero',
    nationality: '🇮🇹',
    continent: 'Europa',
    bio: 'Street food siciliano a Milano.',
    fullBio: 'Nato ai mercati di Palermo, Calogero ha portato la "vastedda" e le arancine a Milano per non far dimenticare il sole della sua terra.',
    avatar: 'https://images.unsplash.com/photo-1533227260875-99d750c3cedb?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    location: 'Milano, Lambrate',
    distance: 0.8,
    specialties: ['Arancine', 'Cannoli'],
    availability: ['10:00 - 20:00'],
    availableDays: [1, 2, 3, 4, 5, 6, 0],
    reviews: [],
    dishes: [{ id: 'd32_1', name: 'Arancina al Ragù', description: 'Palla di riso allo zafferano ripiena di ragù siciliano, piselli e caciocavallo, fritta a regola d\'arte.', price: 4.50, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c32', tags: ['Carne'] }]
  },
  {
    id: 'c33',
    name: 'Emma Watson',
    nationality: '🇬🇧',
    continent: 'Europa',
    bio: 'Pies e Sunday Roast tradizionali.',
    fullBio: 'Emma cucina i piatti della domenica inglese. Shepherd\'s pie e roast beef sono i suoi cavalli di battaglia per scaldare il cuore.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
    location: 'Torino, Centro',
    distance: 1.8,
    specialties: ['Shepherd\'s Pie', 'Fish and Chips'],
    availability: ['12:00 - 15:00'],
    availableDays: [0, 6],
    reviews: [],
    dishes: [{ id: 'd33_1', name: 'Shepherd\'s Pie', description: 'Carne di agnello macinata stufata con verdure e sormontata da una crosta dorata di purè di patate.', price: 14.50, image: 'https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&w=800&q=80', chefId: 'c33', tags: ['Carne'] }]
  },
  {
    id: 'c34',
    name: 'Jordi Alva',
    nationality: '🇪🇸',
    continent: 'Europa',
    bio: 'Tapas e Paella di Valencia.',
    fullBio: 'Jordi crede che la Paella sia un rito sociale. La prepara solo su prenotazione usando il miglior riso bomba di Valencia.',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Bologna, Centro',
    distance: 0.7,
    specialties: ['Paella', 'Tapas'],
    availability: ['19:00 - 23:00'],
    availableDays: [1, 2, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd34_1', name: 'Paella de Marisco', description: 'Riso bomba con calamari, gamberi, cozze e zafferano, cucinato nella classica padella larga.', price: 22.00, image: 'https://images.unsplash.com/photo-1534080564607-c980d49451d7?auto=format&fit=crop&w=800&q=80', chefId: 'c34', tags: ['Pesce', 'Riso'] }]
  },

  // --- AFRICA (10) ---
  {
    id: 'c3',
    name: 'Adunni Oladele',
    nationality: '🇳🇬',
    countryName: 'Nigeria',
    continent: 'Africa',
    bio: 'Il calore di Lagos in ogni piatto.',
    fullBio: 'Adunni è la regina delle spezie. Ha portato il "Party Jollof" della Nigeria a Milano, un riso che profuma di casa e celebrazione.',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    location: 'Milano, Loreto',
    distance: 3.1,
    specialties: ['Jollof Rice', 'Egusi Soup', 'Suya Spiced Skewers'],
    availability: ['12:00 - 21:00'],
    availableDays: [1, 2, 3, 4, 5],
    reviews: [],
    dishes: [
      { id: 'd3_1', name: 'Party Jollof Rice', description: 'Riso a chicco lungo cotto in un sugo di peperoni e pomodori affumicati, servito con pollo fritto speziato.', price: 15.00, image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80', chefId: 'c3', tags: ['Carne', 'Piccante'] },
      { id: 'd3_2', name: 'Suya Beef Skewers', description: 'Spiedini di manzo succulenti, marinati in una polvere speziata a base di arachidi macinate (Kuli-Kuli), zenzero e chili, cotti alla brace.', price: 12.50, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c3', tags: ['Carne', 'Piccante', 'Arachidi'] },
      { id: 'd3_3', name: 'Egusi Soup & Pounded Yam', description: 'Zuppa densa preparata con semi di melone egusi tritati, foglie di zucca, gamberetti secchi e carne, servita con morbido Pounded Yam fatto a mano.', price: 17.00, image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', chefId: 'c3', tags: ['Pesce', 'Carne', 'Tradizionale'] }
    ]
  },
  {
    id: 'c4',
    name: 'Moussa Diouf',
    nationality: '🇸🇳',
    countryName: 'Senegal',
    continent: 'Africa',
    bio: 'Sapori di Dakar e pesce fresco.',
    fullBio: 'Moussa seleziona personalmente il pesce ogni mattina per il suo Thieboudienne. La sua cucina è un omaggio all\'oceano e alla Teranga senegalese.',
    avatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Torino, San Salvario',
    distance: 1.5,
    specialties: ['Thieboudienne', 'Yassa au Poulet', 'Pastels'],
    availability: ['19:00 - 22:00'],
    availableDays: [4, 5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd4_1', name: 'Thieboudienne Rosso', description: 'Il piatto nazionale senegalese: riso cotto nel sugo di pomodoro concentrato con cernia fresca, manioca, carote, cavolo e melanzane locali.', price: 16.50, image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=800&q=80', chefId: 'c4', tags: ['Pesce', 'Riso'] },
      { id: 'd4_2', name: 'Yassa au Poulet', description: 'Cosce di pollo grigliate e poi stufate in un intingolo agrumato di cipolle caramellate, succo di lime fresco, senape e peperoncini del Senegal.', price: 14.00, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', chefId: 'c4', tags: ['Carne', 'Agrumato'] },
      { id: 'd4_3', name: 'Pastels de Poisson', description: 'Sfiziosi fagottini di pasta fritti, ripieni di sgombro fresco tritato e speziato, accompagnati da una salsa dolce-piccante al pomodoro.', price: 8.00, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c4', tags: ['Pesce', 'Antipasti'] }
    ]
  },
  {
    id: 'c8',
    name: 'Fatima El-Amrani',
    nationality: '🇲🇦',
    countryName: 'Marocco',
    continent: 'Africa',
    bio: 'Tagine e Couscous reali.',
    fullBio: 'Fatima usa una tagine di terracotta tramandata da tre generazioni. Le sue spezie arrivano direttamente dal souk di Marrakech.',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    location: 'Palermo, Centro',
    distance: 1.1,
    specialties: ['Tagine', 'Pastilla', 'Couscous Reale'],
    availability: ['19:00 - 21:30'],
    availableDays: [5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd8_1', name: 'Tagine d\'Agnello', description: 'Agnello tenerissimo cotto lentamente con prugne dolci, mandorle tostate e sesamo.', price: 18.00, image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2895?auto=format&fit=crop&w=800&q=80', chefId: 'c8', tags: ['Carne'] },
      { id: 'd8_2', name: 'Pastilla di Pollo', description: 'Un capolavoro agrodolce: strati di croccante sfoglia brick ripieni di pollo sfilacciato, uovo cremoso e mandorle tritate, decorati con cannella.', price: 13.50, image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', chefId: 'c8', tags: ['Pollo', 'Agrodolce'] },
      { id: 'd8_3', name: 'Couscous alle Sette Verdure', description: 'Tradizionale couscous lavorato a mano e condito con una ricca varietà di verdure dell\'orto stufate nel loro brodo aromatico alle spezie.', price: 14.00, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c8', tags: ['Vegetariano'] }
    ]
  },
  {
    id: 'c13',
    name: 'Amara Bekele',
    nationality: '🇪🇹',
    countryName: 'Etiopia',
    continent: 'Africa',
    bio: 'Zighinì servito su Injera fatta in casa.',
    fullBio: 'Amara prepara l\'Injera lasciando fermentare il teff per 3 giorni. Il suo Zighinì è un viaggio sensoriale tra i sapori di Addis Abeba.',
    avatar: 'https://images.unsplash.com/photo-1531123414780-f74242c2b052?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    location: 'Roma, Esquilino',
    distance: 1.5,
    specialties: ['Zighinì', 'Doro Wat', 'Sambusa Veg'],
    availability: ['18:00 - 22:00'],
    availableDays: [3, 4, 5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd13_1', name: 'Zighinì di Manzo', description: 'Stufato di manzo piccante al berberé, servito con uova sode su una grande injera spugnosa.', price: 16.00, image: 'https://images.unsplash.com/photo-1542354256-4b68e7d7f26c?auto=format&fit=crop&w=800&q=80', chefId: 'c13', tags: ['Carne', 'Piccante'] },
      { id: 'd13_2', name: 'Doro Wat delle Feste', description: 'Stufato denso di pollo intero marinato al limone, cotto a fuoco dolce in cipolle in purea e berberé etiope, servito con uova sode e injera.', price: 17.50, image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', chefId: 'c13', tags: ['Carne', 'Piccante', 'Tradizionale'] },
      { id: 'd13_3', name: 'Sambusa con Lenticchie (Tris)', description: 'Triangoli croccanti di pasta fillo ripieni di lenticchie speziate al cumino, aglio, zenzero e coriandolo fritto.', price: 7.50, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c13', tags: ['Vegetariano', 'Antipasti'] }
    ]
  },
  {
    id: 'c5',
    name: 'Koffi Yao',
    nationality: '🇨🇮',
    countryName: 'Costa d\'Avorio',
    continent: 'Africa',
    bio: 'Il re dell\'Attiéké a Napoli.',
    fullBio: 'Koffi porta la cucina di strada ivoriana a Napoli. Il suo Garba è diventato una leggenda tra gli appassionati di cucina etnica.',
    avatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Napoli, Centro',
    distance: 2.7,
    specialties: ['Garba', 'Alloco con Pesce', 'Kédjénou di Pollo'],
    availability: ['12:30 - 15:00'],
    availableDays: [1, 3, 5, 6],
    reviews: [],
    dishes: [
      { id: 'd5_1', name: 'Attiéké con Pesce Fritto (Garba)', description: 'Couscous di manioca fermentata (Attiéké) soffice e leggermente acidulo, servito con trancio di tonno fritto croccante, cipolla rossa a cubetti, pomodori freschi e peperoncino ivoriano.', price: 12.00, image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80', chefId: 'c5', tags: ['Pesce', 'Manioca', 'Ivoriano'], ingredients: ['Attiéké (Manioca fermentata)', 'Trancio di Tonno fresco', 'Cipolla rossa', 'Pomodoro fresco', 'Peperoncino piquant', 'Olio vegetale', 'Aromi ivoriani'], preparation: 'L\'Attiéké viene cotto al vapore secondo la tradizione abidjanese. Il tonno viene infarinato leggermente e fritto in olio bollente fino a doratura croccante, servito con brunoise di cipolle e pomodoro.' },
      { id: 'd5_2', name: 'Alloco con Orata Grigliata', description: 'Tris di platani dolci fritti a tocchetti serviti con orata intera alla griglia, salsa cipolla-pomodoro e peperoncino piccante frantumato.', price: 16.00, image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', chefId: 'c5', tags: ['Pesce', 'Frutta'] },
      { id: 'd5_3', name: 'Kédjénou di Pollo', description: 'Stufato aromatico ivoriano di pollo cotto dolcemente nel suo vapore in pentola d\'argilla chiusa ermeticamente con melanzane, pomodoro fresco e zenzero.', price: 14.50, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', chefId: 'c5', tags: ['Carne', 'Tradizionale'] }
    ]
  },
  {
    id: 'c6',
    name: 'Nadia Mansour',
    nationality: '🇪🇬',
    countryName: 'Egitto',
    continent: 'Africa',
    bio: 'Antiche ricette del Cairo.',
    fullBio: 'Nadia cucina il Koshary perfetto: l\'equilibrio tra amido e salsa di pomodoro acidula è la sua missione di vita.',
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Roma, Esquilino',
    distance: 0.8,
    specialties: ['Koshary', 'Ta\'ameya', 'Basbousa'],
    availability: ['11:00 - 19:00'],
    availableDays: [1, 2, 3, 4, 5, 6],
    reviews: [],
    dishes: [
      { id: 'd6_1', name: 'Koshary Reale', description: 'Riso, lenticchie, pasta e ceci con una salsa al pomodoro speziata e pioggia di cipolle fritte.', price: 9.50, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c6', tags: ['Vegetariano'] },
      { id: 'd6_2', name: 'Ta\'ameya Veg dell\'Antico Cairo', description: 'I famosissimi falafel egiziani dorati preparati esclusivamente con fave decorticate tritate, coriandolo fresco fritto, aglio, prezzemolo e semi di sesamo.', price: 8.00, image: 'https://images.unsplash.com/photo-1547928576-a4a33237ecd3?auto=format&fit=crop&w=800&q=80', chefId: 'c6', tags: ['Vegetariano', 'Antipasti'] },
      { id: 'd6_3', name: 'Basbousa al Miele', description: 'Tradizionale e sofficissimo dolce egiziano di semolino bagnato generosamente con sciroppo caldo di fiori d\'arancio ed miele, sormontato da mandorle.', price: 6.50, image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', chefId: 'c6', tags: ['Dolci'] }
    ]
  },
  {
    id: 'c7',
    name: 'Kwame Mensah',
    nationality: '🇬🇭',
    countryName: 'Ghana',
    continent: 'Africa',
    bio: 'Autentico Ghana Jollof e Waakye.',
    fullBio: 'Kwame è un purista. Sostiene che il Jollof del Ghana sia superiore a quello nigeriano e sfida chiunque a provarlo.',
    avatar: 'https://images.unsplash.com/photo-1583336137348-82836e28d6c7?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Bologna, Bolognina',
    distance: 3.5,
    specialties: ['Waakye', 'Red Red Stew', 'Kelewele Speziato'],
    availability: ['17:00 - 22:00'],
    availableDays: [0, 2, 4, 5, 6],
    reviews: [],
    dishes: [
      { id: 'd7_1', name: 'Waakye Mix', description: 'Riso e fagioli cotti con foglie di sorgo per un colore scuro naturale, con carne di capra stufata.', price: 14.00, image: 'https://images.unsplash.com/photo-1542354256-4b68e7d7f26c?auto=format&fit=crop&w=800&q=80', chefId: 'c7', tags: ['Carne'] },
      { id: 'd7_2', name: 'Red Red Stew', description: 'Delizioso spezzatino di fagioli dell\'occhio cotti a fuoco lento in olio di palma rosso purissimo con pomodori freschi, servito con platani fritti dolcissimi.', price: 12.00, image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2895?auto=format&fit=crop&w=800&q=80', chefId: 'c7', tags: ['Vegetariano', 'Tradizionale'] },
      { id: 'd7_3', name: 'Kelewele Speziato ghanese', description: 'Cubetti dorati di platano maturo fritti, marinati precedentemente con zenzero fresco tritato, noce moscata, peperoncino di Cayenna selvatico e limone.', price: 7.00, image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80', chefId: 'c7', tags: ['Vegetariano', 'Antipasti'] }
    ]
  },
  {
    id: 'c21',
    name: 'Zalika Juma',
    nationality: '🇰🇪',
    countryName: 'Kenya',
    continent: 'Africa',
    bio: 'Cucina swahili di Mombasa.',
    fullBio: 'Zalika porta il profumo di cocco e spezie della costa keniota. Il suo Pilau è famoso per la delicatezza degli aromi.',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    location: 'Firenze, Rifredi',
    distance: 2.5,
    specialties: ['Beef Pilau', 'Swahili Nyama Choma', 'Samosa di Mombasa'],
    availability: ['19:00 - 22:00'],
    availableDays: [5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd21_1', name: 'Beef Pilau', description: 'Riso profumato con cannella, cardamomo e chiodi di garofano, cotto con pezzi di manzo tenero.', price: 14.00, image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80', chefId: 'c21', tags: ['Carne', 'Riso'] },
      { id: 'd21_2', name: 'Swahili Nyama Choma', description: 'Saporita carne di pecora o capra marinata alle spezie di Mombasa, cotta lentamente alla griglia, servita con polenta Ugali e insalata fresca kachumbari.', price: 17.00, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c21', tags: ['Carne', 'Grigliato'] },
      { id: 'd21_3', name: 'Samosa di Carne Swahili (Tris)', description: 'Fagottini triangolari di pasta stesi a mano, ripieni di carne bovina macinata aromatizzata alla cipolla, prezzemolo, coriandolo ed essenza di zenzero.', price: 8.00, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c21', tags: ['Carne', 'Antipasti'] }
    ]
  },
  {
    id: 'c23',
    name: 'Samuel Eto\'o',
    nationality: '🇨🇲',
    countryName: 'Camerun',
    continent: 'Africa',
    bio: 'Ndolé autentico e platano fritto.',
    fullBio: 'Per Samuel cucinare il Ndolé è un atto di fede. Le foglie amare devono essere lavate sette volte per raggiungere il gusto perfetto.',
    avatar: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Torino, Cenisia',
    distance: 2.1,
    specialties: ['Ndolé con Gamberi', 'Poulet DG', 'Beignets Camerunensi'],
    availability: ['18:30 - 21:30'],
    availableDays: [2, 4, 6],
    reviews: [],
    dishes: [
      { id: 'd23_1', name: 'Ndolé con Gamberi', description: 'Foglie amare stufate con pasta di arachidi, spezie e gamberi freschi saltati.', price: 17.50, image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80', chefId: 'c23', tags: ['Pesce'] },
      { id: 'd23_2', name: 'Poulet DG Reale', description: 'Saporito pollo marinato saltato in un delizioso mix di platani dolci fritti, carote grigliate, piccoli peperoni e fagiolini freschi.', price: 15.50, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', chefId: 'c23', tags: ['Carne', 'Frutta'] },
      { id: 'd23_3', name: 'Beignets Haricot calamaro', description: 'Soffici frittelle dolci dorate camerunensi fatte in casa servite calde con salsa speziata di fagioli neri stufati aromati.', price: 8.50, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c23', tags: ['Dolci', 'Tradizionale'] }
    ]
  },
  {
    id: 'c26',
    name: 'Leila Trabelsi',
    nationality: '🇹🇳',
    countryName: 'Tunisia',
    continent: 'Africa',
    bio: 'Couscous piccante e Brik.',
    fullBio: 'Leila domina l\'arte dell\'Harissa fatta in casa. Il suo couscous è leggerissimo e incredibilmente saporito.',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Trapani, Centro',
    distance: 0.3,
    specialties: ['Couscous di Pesce', 'Brik Tunisino', 'Ojja Merguez'],
    availability: ['11:00 - 21:00'],
    availableDays: [1, 2, 3, 4, 5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd26_1', name: 'Couscous di Pesce', description: 'Semola incocciata a mano, servita con brodo di pesce piccante e pescato locale freschissimo.', price: 18.00, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c26', tags: ['Pesce', 'Piccante'] },
      { id: 'd26_2', name: 'Brik Tunisino all\'Uovo (Duo)', description: 'Super croccante sfoglia triangolare "malsouka" fritta caldissima ripiena di tonno sott\'olio, capperi di Trapani, uovo cremoso e prezzemolo.', price: 9.00, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c26', tags: ['Pesce', 'Antipasti'] },
      { id: 'd26_3', name: 'Ojja piccante con Merguez', description: 'Uova affogate cotte dolcemente in un denso sugo speziato di pomodori e peperoni verdi, insaporito con Harissa tunisina artigianale e pezzetti di salsiccia di agnello Merguez.', price: 14.50, image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', chefId: 'c26', tags: ['Carne', 'Piccante'] }
    ]
  },

  // --- ASIA (8) ---
  {
    id: 'c2',
    name: 'Kenji Yamamoto',
    nationality: '🇯🇵',
    continent: 'Asia',
    bio: 'Sushi master di Osaka.',
    fullBio: 'Kenji ha servito sushi nei mercati di Osaka per 20 anni prima di aprire la sua "cucina casalinga" a Milano. Il suo segreto è l\'aceto di riso segreto.',
    avatar: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Milano, Brera',
    distance: 2.5,
    specialties: ['Sushi', 'Ramen'],
    availability: ['18:30 - 23:00'],
    availableDays: [0, 2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd2_1', name: 'Sushi Moriawase', description: 'Selezione di 12 pezzi tra Nigiri e Sashimi con pesce abbattuto freschissimo di qualità premium.', price: 24.00, image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80', chefId: 'c2', tags: ['Pesce', 'Sushi'] }]
  },
  {
    id: 'c15',
    name: 'Siriwat Chai',
    nationality: '🇹🇭',
    continent: 'Asia',
    bio: 'Sapori di Bangkok.',
    fullBio: 'Siriwat ha imparato l\'arte dello street food nei canali di Bangkok. I suoi piatti sono un equilibrio millimetrico tra dolce, agro e piccante.',
    avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Bologna, Centro',
    distance: 1.1,
    specialties: ['Pad Thai', 'Green Curry'],
    availability: ['19:00 - 23:00'],
    availableDays: [1, 2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd15_1', name: 'Pad Thai Gamberi', description: 'Tagliolini di riso saltati con gamberi, uova, tofu, germogli di soia e granella di arachidi.', price: 14.00, image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80', chefId: 'c15', tags: ['Pesce', 'Riso'] }]
  },
  {
    id: 'c16',
    name: 'Ji-Soo Kim',
    nationality: '🇰🇷',
    continent: 'Asia',
    bio: 'Bibimbap e fermentazioni.',
    fullBio: 'Ji-Soo prepara il Kimchi seguendo l\'antica ricetta di sua nonna. Ogni vasetto fermenta almeno 3 mesi prima di essere servito.',
    avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Firenze, Santa Croce',
    distance: 0.9,
    specialties: ['Bibimbap', 'Kimchi'],
    availability: ['18:00 - 22:00'],
    availableDays: [1, 2, 4, 5],
    reviews: [],
    dishes: [{ id: 'd16_1', name: 'Bibimbap Classico', description: 'Riso caldo in ciotola con verdure saltate, carne marinata, uovo occhio di bue e salsa gochujang.', price: 15.50, image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80', chefId: 'c16', tags: ['Carne', 'Piccante'] }]
  },
  {
    id: 'c17',
    name: 'Priya Sharma',
    nationality: '🇮🇳',
    continent: 'Asia',
    bio: 'Il meglio del Punjab.',
    fullBio: 'Priya macina le sue spezie ogni giorno. Il suo Butter Chicken è un inno alla cremosità e alla tradizione indiana del Nord.',
    avatar: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Verona, Centro',
    distance: 3.3,
    specialties: ['Butter Chicken', 'Biryani'],
    availability: ['19:00 - 22:00'],
    availableDays: [2, 3, 4, 5, 6, 0],
    reviews: [],
    dishes: [{ id: 'd17_1', name: 'Butter Chicken', description: 'Pollo cotto nel tandoori e poi tuffato in una salsa ricca di pomodoro, burro e crema di spezie.', price: 13.50, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b0ae398?auto=format&fit=crop&w=800&q=80', chefId: 'c17', tags: ['Carne'] }]
  },
  {
    id: 'c18',
    name: 'Samir Haddad',
    nationality: '🇱🇧',
    continent: 'Asia',
    bio: 'Mezzé libanesi e Hummus.',
    fullBio: 'Samir crede nella convivialità. I suoi vassoi di Mezzé sono pensati per essere condivisi al centro della tavola.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Milano, Wagner',
    distance: 2.1,
    specialties: ['Hummus', 'Kibbeh'],
    availability: ['11:30 - 20:30'],
    availableDays: [1, 2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd18_1', name: 'Mix di Mezzé', description: 'Un assortimento di Hummus, Babaganoush, Falafel croccanti e pane pita appena sfornato.', price: 12.00, image: 'https://images.unsplash.com/photo-1547928576-a4a33237ecd3?auto=format&fit=crop&w=800&q=80', chefId: 'c18', tags: ['Vegetariano'] }]
  },
  {
    id: 'c19',
    name: 'Minh Nguyen',
    nationality: '🇻🇳',
    continent: 'Asia',
    bio: 'Pho profumato e Spring Rolls.',
    fullBio: 'Minh cuoce il brodo del suo Pho per 12 ore con ossa di manzo e spezie tostate per un gusto profondo e pulito.',
    avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Torino, Lingotto',
    distance: 4.5,
    specialties: ['Pho', 'Banh Mi'],
    availability: ['12:00 - 15:00'],
    availableDays: [1, 2, 3, 4, 5],
    reviews: [],
    dishes: [{ id: 'd19_1', name: 'Pho Bo', description: 'Zuppa di noodles di riso in brodo di manzo profumato con cannella, anice stellato e zenzero.', price: 14.50, image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80', chefId: 'c19', tags: ['Carne', 'Zuppa'] }]
  },
  {
    id: 'c20',
    name: 'Osman Yilmaz',
    nationality: '🇹🇷',
    continent: 'Asia',
    bio: 'Baklava e Kebab gourmet.',
    fullBio: 'Osman è un pasticcere di terza generazione. La sua pasta fillo per il Baklava è sottile come la carta velina.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Genova, Porto',
    distance: 1.3,
    specialties: ['Baklava', 'Lahmacun'],
    availability: ['10:00 - 22:00'],
    availableDays: [1, 2, 3, 4, 5, 6, 0],
    reviews: [],
    dishes: [{ id: 'd20_1', name: 'Baklava al Pistacchio', description: 'Strati croccanti di pasta fillo, miele di fiori e pistacchi di Bronte selezionati.', price: 8.00, image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', chefId: 'c20', tags: ['Dolci'] }]
  },
  {
    id: 'c35',
    name: 'Wei Chen',
    nationality: '🇨🇳',
    continent: 'Asia',
    bio: 'Dumplings e anatra alla pechinese.',
    fullBio: 'Wei porta la vera cucina di Pechino a Prato. I suoi ravioli sono chiusi a mano uno ad uno con tecnica magistrale.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Prato, Centro',
    distance: 1.2,
    specialties: ['Dumplings', 'Peking Duck'],
    availability: ['12:00 - 22:00'],
    availableDays: [1, 2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd35_1', name: 'Dumplings di Maiale', description: 'Ravioli al vapore ripieni di maiale, zenzero e cipollotto, serviti con salsa di soia e aceto nero.', price: 9.00, image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80', chefId: 'c35', tags: ['Carne'] }]
  },

  // --- AMERICHE (8) ---
  {
    id: 'c10',
    name: 'Elena Sanchez',
    nationality: '🇲🇽',
    continent: 'Americhe',
    bio: 'Tacos de la Calle autentici.',
    fullBio: 'Elena ha gestito un taco-truck a Città del Messico per 10 anni. Le sue tortillas sono fatte a mano ogni mattina.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Milano, Isola',
    distance: 1.9,
    specialties: ['Tacos Al Pastor', 'Mole'],
    availability: ['18:00 - 00:00'],
    availableDays: [4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd10_1', name: 'Tacos Al Pastor', description: 'Maiale marinato con achiote e spezie, servito con ananas, coriandolo e cipolla su tortilla di mais.', price: 12.00, image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=800&q=80', chefId: 'c10', tags: ['Carne', 'Piccante'] }]
  },
  {
    id: 'c29',
    name: 'Sofia Lopez',
    nationality: '🇦🇷',
    continent: 'Americhe',
    bio: 'Empanadas e Asado.',
    fullBio: 'Sofia è la maestra delle chiusure delle empanadas (il repulgue). Ogni gusto ha la sua forma specifica per essere riconosciuto.',
    avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Milano, Navigli',
    distance: 1.4,
    specialties: ['Empanadas', 'Chimichurri'],
    availability: ['19:00 - 01:00'],
    availableDays: [4, 5, 6, 0],
    reviews: [],
    dishes: [{ id: 'd29_1', name: 'Tris di Empanadas', description: 'Selezione di tre fagottini argentini: carne salteña, humita (mais) e prosciutto e formaggio.', price: 10.50, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c29', tags: ['Carne'] }]
  },
  {
    id: 'c12',
    name: 'Beatriz Costa',
    nationality: '🇧🇷',
    continent: 'Americhe',
    bio: 'Feijoada e allegria carioca.',
    fullBio: 'Beatriz prepara la Feijoada del sabato come a Rio de Janeiro. Un piatto che richiede 24 ore di preparazione e tanta passione.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Venezia, Mestre',
    distance: 5.0,
    specialties: ['Feijoada', 'Pão de Queijo'],
    availability: ['12:00 - 18:00'],
    availableDays: [6, 0],
    reviews: [],
    dishes: [{ id: 'd12_1', name: 'Feijoada Completa', description: 'Stufato di fagioli neri con tagli scelti di maiale, servito con riso, farofa, arancia e cavolo.', price: 17.00, image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80', chefId: 'c12', tags: ['Carne'] }]
  },
  {
    id: 'c14',
    name: 'Carlos Quispe',
    nationality: '🇵🇪',
    continent: 'Americhe',
    bio: 'Ceviche fresco e Nikkei.',
    fullBio: 'Carlos è un esperto di pesce. Il suo Ceviche usa solo lime fresco spremuto al momento per mantenere l\'acidità perfetta.',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Milano, Lambrate',
    distance: 2.8,
    specialties: ['Ceviche', 'Lomo Saltado'],
    availability: ['12:00 - 20:00'],
    availableDays: [2, 3, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd14_1', name: 'Ceviche Classico', description: 'Pesce bianco marinato in "leche de tigre" con lime, peperoncino, cipolla rossa e coriandolo.', price: 18.50, image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=800&q=80', chefId: 'c14', tags: ['Pesce'] }]
  },
  {
    id: 'c30',
    name: 'John Smith',
    nationality: '🇺🇸',
    continent: 'Americhe',
    bio: 'Slow BBQ e Burgers.',
    fullBio: 'John è un texano doc. Il suo barbecue affumica la carne per 12 ore nel suo smoker professionale domestico.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Napoli, Chiaia',
    distance: 3.0,
    specialties: ['Pulled Pork', 'Burgers'],
    availability: ['18:00 - 22:00'],
    availableDays: [1, 2, 4, 5, 6],
    reviews: [],
    dishes: [{ id: 'd30_1', name: 'Pulled Pork Sandwich', description: 'Spalla di maiale affumicata 12 ore, sfilacciata e servita con salsa BBQ e insalata coleslaw.', price: 13.50, image: 'https://images.unsplash.com/photo-1527324688101-01b1b9a5f781?auto=format&fit=crop&w=800&q=80', chefId: 'c30', tags: ['Carne'] }]
  },
  {
    id: 'c22',
    name: 'Jabari Mbeki',
    nationality: '🇿🇦',
    countryName: 'Sudafrica',
    continent: 'Africa',
    bio: 'Bobotie e sapori della Rainbow Nation.',
    fullBio: 'Jabari porta i sapori multi-culturali di Cape Town. Il suo Bobotie è un equilibrio perfetto di speziato e dolce.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
    location: 'Roma, Eur',
    distance: 6.2,
    specialties: ['Bobotie Classico', 'Chakalaka', 'Salsiccia Boerewors'],
    availability: ['12:00 - 15:00'],
    availableDays: [1, 2, 3, 4, 5],
    reviews: [],
    dishes: [
      { id: 'd22_1', name: 'Bobotie Classico', description: 'Pasticcio di carne speziata con frutta secca e uvetta, sormontato da una crema dorata all\'uovo.', price: 15.00, image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=800&q=80', chefId: 'c22', tags: ['Carne'] },
      { id: 'd22_2', name: 'Chakalaka & Pap', description: 'Contorno piccante e coloratissimo a base di fagioli stufati, carote, peperoni e spezie calde, servito con la classica polenta bianca di mais (Pap) densa.', price: 11.50, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c22', tags: ['Vegetariano', 'Piccante'] },
      { id: 'd22_3', name: 'Spiedini di Boerewors alla griglia', description: 'Salsiccia tradizionale sudafricana artigianale a forma di spirale, preparata con carne bovina e suina speziata al coriandolo, chiodi di garofano e noce moscata.', price: 14.00, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c22', tags: ['Carne', 'Grigliato'] }
    ]
  },
  {
    id: 'c24',
    name: 'Bantu Kabange',
    nationality: '🇨🇩',
    countryName: 'R.D. Congo',
    continent: 'Africa',
    bio: 'Moambe e sapori equatoriali.',
    fullBio: 'Bantu usa solo puro olio di palma africano per il suo Pollo alla Moambe, garantendo il sapore denso e unico del Congo.',
    avatar: 'https://images.unsplash.com/photo-1531123414780-f74242c2b052?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Padova, Centro',
    distance: 1.2,
    specialties: ['Moambe', 'Fufu', 'Liboke de Poisson'],
    availability: ['19:00 - 22:00'],
    availableDays: [1, 3, 5],
    reviews: [],
    dishes: [
      { id: 'd24_1', name: 'Pollo alla Moambe', description: 'Pollo stufato in una ricca salsa di noci di palma con spinaci selvatici e manioca.', price: 16.00, image: 'https://images.unsplash.com/photo-1542354256-4b68e7d7f26c?auto=format&fit=crop&w=800&q=80', chefId: 'c24', tags: ['Carne'] },
      { id: 'd24_2', name: 'Liboke de Poisson', description: 'Pescato fresco di giornata cotto intero al cartoccio in profumate foglie di banano selvatico con pomodorini di collina, aglio, cipolla ed essenza di zenzero fresco.', price: 17.50, image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=800&q=80', chefId: 'c24', tags: ['Pesce'] },
      { id: 'd24_3', name: 'Fufu caldissimo con Mikate', description: 'Tipico fufu soffice di farina di manioca servito con mikate croccanti (frittelle dorate congolesi aromatizzate alla vaniglia dolce).', price: 7.00, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c24', tags: ['Vegetariano', 'Dolci'] }
    ]
  },
  {
    id: 'c25',
    name: 'Anika Keita',
    nationality: '🇲🇱',
    countryName: 'Mali',
    continent: 'Africa',
    bio: 'Maafe cremoso alle arachidi.',
    fullBio: 'Anika è famosa per la setosità della sua crema di arachidi, che prepara tostando i semi a mano.',
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    location: 'Vicenza, Centro',
    distance: 4.8,
    specialties: ['Maafe', 'Yassa Maliana', 'Widjila'],
    availability: ['12:00 - 15:00'],
    availableDays: [1, 2, 4],
    reviews: [],
    dishes: [
      { id: 'd25_1', name: 'Maafe di Agnello', description: 'Spezzatino di agnello in una densa e saporita salsa di arachidi e pomodoro, servito con riso bianco.', price: 14.50, image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2895?auto=format&fit=crop&w=800&q=80', chefId: 'c25', tags: ['Carne', 'Piccante'] },
      { id: 'd25_2', name: 'Yassa di Pesce alla maliana', description: 'Filetto di pesce persico freschissimo marinato al limone, frullato riccamente e cotto con cipolle dorate caramellate, servito con purè di platano bollito.', price: 15.00, image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=800&q=80', chefId: 'c25', tags: ['Pesce', 'Agrumato'] },
      { id: 'd25_3', name: 'Widjila al Vapore', description: 'Insolito e tipico pane brioche cotto squisitamente a vapore sopra una pentola che bolle con salsa speziata di pomodoro ed erbe selvatiche.', price: 7.50, image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80', chefId: 'c25', tags: ['Vegetariano', 'Antipasti'] }
    ]
  },
  {
    id: 'c40',
    name: 'Faduma Omar',
    nationality: '🇸🇴',
    countryName: 'Somalia',
    continent: 'Africa',
    bio: 'Riso Bariis Iskukaris e Sambusa dorate.',
    fullBio: 'Faduma ha imparato l\'arte delle spezie Xawaash da sua nonna a Mogadiscio. Il suo pilau somalo racchiude una storia di commercio e tradizione profumatissima.',
    avatar: 'https://images.unsplash.com/photo-1531123414780-f74242c2b052?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    location: 'Milano, Wagner',
    distance: 2.2,
    specialties: ['Bariis Iskukaris', 'Somali Sambusa', 'Somali Halva'],
    availability: ['12:00 - 15:00', '19:00 - 22:00'],
    availableDays: [2, 3, 4, 5, 6],
    reviews: [],
    dishes: [
      { id: 'd40_1', name: 'Bariis Iskukaris aromatico', description: 'Cremoso riso basmati somalo aromatizzato con la storica miscela Xawaash (cumino, cardamomo, chiodi di garofano), ciliegino, uvetta dolce, cipolla fritta e servito con stufato d\'agnello tenerissimo.', price: 16.00, image: 'https://images.unsplash.com/photo-1542354256-4b68e7d7f26c?auto=format&fit=crop&w=800&q=80', chefId: 'c40', tags: ['Carne', 'Saporito'] },
      { id: 'd40_2', name: 'Sambusa Somale Croccante (Tris)', description: 'Scrigni di sfoglia fritti preparati a mano ripieni di carne di manzo tritata finissima, aromatizzati con cipolle rosse fresche, aglio, cumino e coriandolo.', price: 7.50, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80', chefId: 'c40', tags: ['Carne', 'Antipasti'] }
    ]
  },
  {
    id: 'c41',
    name: 'Tendry Rasolonjatovo',
    nationality: '🇲🇬',
    countryName: 'Madagascar',
    continent: 'Africa',
    bio: 'Profumo di vaniglia naturale e Romazava.',
    fullBio: 'Tendry unisce l\'influenza della cucina asiatica ed africana tipica del Madagascar. Sceglie solo foglie verdi freschissime per preparare il piatto nazionale, il Romazava.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    location: 'Roma, Trastevere',
    distance: 1.9,
    specialties: ['Romazava Tradizionale', 'Pollo al Cocco e Vaniglia'],
    availability: ['18:30 - 22:30'],
    availableDays: [1, 2, 4, 5, 6, 0],
    reviews: [],
    dishes: [
      { id: 'd41_1', name: 'Romazava Tradizionale', description: 'Lo straordinario stufato nazionale del Madagascar preparato con carne di manzo, zenzero fresco, aglio e un mix straordinario di foglie verdi leggermente piccanti.', price: 16.50, image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=800&q=80', chefId: 'c41', tags: ['Carne', 'Tradizionale'] },
      { id: 'd41_2', name: 'Pollo al Cocco e Vaniglia', description: 'Bocconcini di pollo ruspante stufati dolcemente in latte di cocco cremoso, zenzero fresco, curcuma dorata ed un tocco profumatissimo di baccelli di vaniglia bourbon del Madagascar.', price: 15.00, image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80', chefId: 'c41', tags: ['Carne', 'Cocco'] }
    ]
  }
];
